### PR TITLE
Svelte transition animations

### PR DESCRIPTION
**Pull request by SteveAndreou**
Removed CSS animations, replaced with Svelte/transition
Fade in on creation, slide out to the left on removal.

### CODE REVIEW

**Comment by negue** [comment]
Could you rebuild it by using https://animate.style  or something a like? 

With a css-only animations library its easier to pick what animation someone wants to have instead of choosing a svelte animation and then having to rebuild this todolist again.

Sorry that you already put work on this svelte animation :(

**Comment by SteveAndreou** [comment]
We might be able to, it sounds a bit tricky. I only just started learning Svelte today 🤔

Maybe we can keep this for today and use it as a stepping stone forward to eventually having the animate.style library available for both in and out transitions.

Edit: We can also keep the issue open, maybe someone else knows a good way to make it work

**Comment by negue** [comment]
I think using the css class is a bit harder than I expected, for the "out animations" those classes would need to be applied and waited until the animation is done and only then the entry could be removed  so I'll create a new issue for it.

**Comment by negue** [comment]
LGTM 👍 

I only had an issue, if you had 2 items, and you deleted the 1st one , it got removed at top and then the animation kicked in.

But I dont think this is something of your fault.

Thanks for the contribution, again! :)

**Pull request merged**
